<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
data(iris)
```

```{r}
encuesta1 <- readSPSS("F:/Clase_de_R_4/Enctran.sav", rownames=FALSE, stringsAsFactors=TRUE, tolower=FALSE)
```

```{r}
library(abind, pos=17)
```


```{r}
local({
  .Table <- xtabs(~CURSO+VEHICULO, data=encuesta1)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~CURSO+VEHICULO, data=encuesta1)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nRow percentages:\n")
  print(rowPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~CURSO+VEHICULO, data=encuesta1)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nRow percentages:\n")
  print(rowPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

